// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getMultiDayRates
NumericMatrix getMultiDayRates(NumericMatrix prices, bool continuous);
RcppExport SEXP estudy2_getMultiDayRates(SEXP pricesSEXP, SEXP continuousSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type prices(pricesSEXP);
    Rcpp::traits::input_parameter< bool >::type continuous(continuousSEXP);
    __result = Rcpp::wrap(getMultiDayRates(prices, continuous));
    return __result;
END_RCPP
}
// getSingleDayRates
NumericMatrix getSingleDayRates(NumericMatrix prices, bool continuous);
RcppExport SEXP estudy2_getSingleDayRates(SEXP pricesSEXP, SEXP continuousSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type prices(pricesSEXP);
    Rcpp::traits::input_parameter< bool >::type continuous(continuousSEXP);
    __result = Rcpp::wrap(getSingleDayRates(prices, continuous));
    return __result;
END_RCPP
}
