# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getMultiDayRates <- function(prices, continuous, Open) {
    .Call('_estudy2_getMultiDayRates', PACKAGE = 'estudy2', prices, continuous, Open)
}

getSingleDayRates <- function(prices, continuous) {
    .Call('_estudy2_getSingleDayRates', PACKAGE = 'estudy2', prices, continuous)
}

