# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getContinuousRates <- function(prices) {
    .Call('estudy2_getContinuousRates', PACKAGE = 'estudy2', prices)
}

getDiscreteRates <- function(prices) {
    .Call('estudy2_getDiscreteRates', PACKAGE = 'estudy2', prices)
}

