# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetContinuousRates <- function(prices) {
    .Call('estudy2_GetContinuousRates', PACKAGE = 'estudy2', prices)
}

